### ISSUE TITLE
Modulation Index value

### ISSUE THREAD

**Issue by cristinabenetton** [sccn/PACTools#14]
### **Modulation Index value**

Thank you for the help with the previous issue.

I have one more question, because maybe I am doing something wrong. After computing PAC, when I plot the PAC estimation (through Comodulogram button), is there a way in which I can also visualize the **modulation index value** to then do statistics on it?

**Comment by nucleuscub** [comment]
Hi @cristinabenetton , yes, there is a way to retrieve the numeric values from the PAC computation. Take a look at this section [here](https://github.com/sccn/PACTools#structure-of-outputs) in the tutorial for details.
 Hope this helps, 
R

**Comment by GitTriplegolds** [comment]
Hello, I have the same problem. It is stated in the manual that after the Kullback-Leibler Modulation Index is used, the output dimension is single value, but I can't find this single value in the workspace of matlab. It is a matrix or a three-dimensional cell matrix. May I ask how to obtain this specific single value so that later statistical analysis can be carried out?
